### PR TITLE
fix: update comments position and fix creating first comment

### PR DESCRIPTION
**Pull request by afonsovinicius**
1 - update comments position;
2 - fix creating first comment - you can't write the first comment ;

### CODE REVIEW

**Comment by SuperViz-Dev** [comment]
Total Coverage: <b>98.54%</b>

<details>
	<summary>Coverage Report</summary>
	<table>
			<tbody>
				<tr><th>File</th>
<th>Branch</th>
<th>Funcs</th>
<th>Lines</th>
<th>Uncovered Lines</th></tr>
				<tr><td colspan='5'><b>src</b></td></tr><tr><td colspan='5'><b>src/web-components</b></td></tr><tr><td colspan='5'><b>src/web-components/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>80.52%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L29>29</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L30>30</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L43>43</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L44>44</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L50>50</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L51>51</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L52>52</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L53>53</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L54>54</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/index.ts#L55>55</a></td></tr><tr><td colspan='5'><b>src/web-components/base/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/icon-button.style.ts'>icon-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/sv-hr.style.ts'>sv-hr.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/typography.style.ts'>typography.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/base/styles/variables.style.ts'>variables.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts'>comments.ts</a></td>
<td><b>92.86%</b></td>
<td><b>87.50%</b></td>
<td><b>98.26%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L45>45</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L46>46</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/comments.ts#L62>62</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-filter.ts'>annotation-filter.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts'>annotation-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>96.64%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L154>154</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L155>155</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L156>156</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L157>157</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L158>158</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L159>159</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L160>160</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-item.ts#L161>161</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts'>annotation-pin.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>94.24%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L104>104</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L109>109</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L110>110</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L111>111</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L112>112</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L163>163</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L164>164</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L165>165</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L228>228</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L62>62</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L63>63</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L64>64</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L65>65</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-pin.ts#L66>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/annotation-resolved.ts'>annotation-resolved.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts'>comment-input.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>99.12%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L93>93</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-input.ts#L94>94</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/comment-item.ts'>comment-item.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts'>content.ts</a></td>
<td><b>96.15%</b></td>
<td><b>81.82%</b></td>
<td><b>88.71%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L104>104</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L105>105</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L35>35</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L36>36</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L39>39</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L40>40</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L47>47</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L48>48</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L49>49</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L63>63</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L74>74</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L75>75</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L76>76</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/content.ts#L77>77</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/delete-comment-modal.ts'>delete-comment-modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts'>float-button.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>96.15%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts#L41>41</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts#L61>61</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/float-button.ts#L62>62</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/topbar.ts'>topbar.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/annotation-filter.style.ts'>annotation-filter.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/annotation-item.style.ts'>annotation-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/annotation-pin.style.ts'>annotation-pin.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/annotation-resolved.style.ts'>annotation-resolved.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/comment-input.style.ts'>comment-input.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/comment-item.style.ts'>comment-item.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/comments.style.ts'>comments.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/content.style.ts'>content.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/float-button.style.ts'>float-button.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/powered-by.style.ts'>powered-by.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/css/topbar.style.ts'>topbar.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/comments/utils</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts'>watermark.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><b>90.77%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts#L17>17</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts#L18>18</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts#L19>19</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts#L20>20</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts#L21>21</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/comments/utils/watermark.ts#L22>22</a></td></tr><tr><td colspan='5'><b>src/web-components/dropdown</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/index.style.ts'>index.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/index.ts'>index.ts</a></td>
<td><b>98.47%</b></td>
<td><span>100%</span></td>
<td><b>99.58%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/index.ts#L262>262</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/index.ts#L408>408</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/index.ts#L71>71</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/index.ts#L74>74</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/dropdown/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/hello-world</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/hello-world/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/icon</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/icon/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/icon/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/modal</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/modal/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/modal/modal-container.ts'>modal-container.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/modal/modal.ts'>modal.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/modal/styles</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/modal/styles/index.style.ts'>index.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/tooltip</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/tooltip/index.style.ts'>index.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/tooltip/index.ts'>index.ts</a></td>
<td><b>96.77%</b></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/tooltip/index.ts#L82>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/tooltip/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/who-is-online</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/who-is-online.ts'>who-is-online.ts</a></td>
<td><b>97.12%</b></td>
<td><span>100%</span></td>
<td><b>99.47%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/who-is-online.ts#L327>327</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/who-is-online.ts#L327>327</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/who-is-online.ts#L327>327</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/who-is-online.ts#L328>328</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/who-is-online.ts#L329>329</a></td></tr><tr><td colspan='5'><b>src/web-components/who-is-online/components</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts'>dropdown.ts</a></td>
<td><b>94.87%</b></td>
<td><b>95.45%</b></td>
<td><b>98.95%</b></td>
<td><a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L133>133</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L134>134</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L165>165</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L165>165</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L177>177</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L177>177</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L178>178</a>, <a href=https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/dropdown.ts#L179>179</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/components/types.ts'>types.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td colspan='5'><b>src/web-components/who-is-online/css</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/css/dropdown.style.ts'>dropdown.style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/css/index.ts'>index.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/SuperViz/sdk/blob/undefined/src/web-components/who-is-online/css/who-is-online-style.ts'>who-is-online-style.ts</a></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td><span>100%</span></td>
<td></td></tr>
			</tbody>
		</table>
		
</details>

**Review by carlossantos74 — APPROVED** [review]

**Pull request merged**
